### ISSUE TITLE
Deleting Merged Repos

### ISSUE THREAD

**Issue by aintnorest** [aintnorest/ubiquitous-spoon#10]
Just curious I've continued to work in branches after they've been merged and I've deleted branches after merge and rebranched from master. I prefer deleting branches after a merge and recreating / creating a new branch to start new work. That prefrence isn't a big deal though and I wanted to ask what you were use to / wanted to do for this?

**Comment by chrisdopuch** [comment]
Yeah my usual workflow at my job is to delete branches once they've been merged
