### ISSUE TITLE
Need to wait till websocket opens before sending a sign in.

### ISSUE THREAD

**Issue by aintnorest** [aintnorest/ubiquitous-spoon#7]
I reimplemented things without socket.io just using web sockets / webRTC as it was giving me some troubles with debugging and duplicate messages. It keeps the same api but it shows a problem that I think socket.io would have if it wasn't running on local.

    export function signIn() {
        return (dispatch, getState) => {
            const socketConfig = {forceNew: false, multiplex: false};
            socketProxy = new SocketProxy(serverURL, socketConfig);
            const userName = getState().appReducer.userName;
            return socketProxy.signIn(userName).then(() => {
                dispatch(setErrorMessage(null));
                dispatch(setSignedIn(true));
                dispatch(redirect('/foo'));
            }).catch((e) => {
                dispatch(setErrorMessage(e.reason));
                dispatch(setSignedIn(false));
            });
        };
    }

 creating / opening a websocket is an async event.  if you try to call signIn too quickly it should fail.  It's not a huge deal just either need to wait for the open event or just call it earlier and check that is open before initiating it.

    const serverURL = 'ws://localhost:4000';
    let socketProxy = new SocketProxy(serverURL);

    socketProxy.ws.onopen = function() {
        console.log('socket open!');
    }

    export function signIn() {
        return (dispatch, getState) => {
            const userName = getState().appReducer.userName;
            return socketProxy.signIn(userName).then(() => {
                dispatch(setErrorMessage(null));
                dispatch(setSignedIn(true));
                dispatch(redirect('/foo'));
            }).catch((e) => {
                dispatch(setErrorMessage(e.reason));
                dispatch(setSignedIn(false));
            });
        };
    }
I did that just to test if it was working. It doesnt take into account relogging in because the disconnect closes the socket so when u go to sign in the second time it will fail. super simple fix would be to create a new socket at same let after disconnect.
This is all a fix for something that isn't broken until i merge those changes in but I believe it will error in the same way with socket.io when not on local.

**Comment by chrisdopuch** [comment]
Good catch, I will push up a fix some time to the branch and then merge it in. 
Next step for me is changing the /foo page to something like /chat and then show a view with a list of users, and a chat window with a text input.
